version: "3.6"

services:
  app:
    build: .
    tty: true
    environment:
      WATCH: '1'
      LIVERELOAD_PORT: 35729
    ports:
      - 80:80
      - 35729:35729
    volumes:
      - ./.eslintrc.js:/code/.eslintrc.js
      - ./stylelint.config.js:/code/stylelint.config.js
      - ./package.json:/code/package.json
      - ./webpack.common.js:/code/webpack.common.js
      - ./webpack.prod.js:/code/webpack.prod.js
      - ./webpack.dev.js:/code/webpack.dev.js
      - ./dist:/code/dist
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./src:/code/src


